server.port=21126
spring.datasource.url=jdbc:postgresql://localhost:5432/gen_1e9802722e6b
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=900000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.sql.init.mode=never
management.endpoints.web.exposure.include=health
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
server.forward-headers-strategy=framework
app.secret.admin-api-key=${ADMIN_API_KEY:590b17eb-5669-42e1-9667-ef9f24b530d78c342f73-2a9a-44a5-8df8-8381c23a8d9a}
